run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/brandon/mcp-email
  govet:
    check-shadowing: true
  misspell:
    locale: US
  lll:
    line-length: 120
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  unconvert:
    suggestions: true
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/mcp/server\.go
      text: "Error return value of .((os\\.stdout|os\\.stderr|os\\.Stdin)\\.(Read|Write|Close)|.*\\.Close|.*\\.Flush|os\\.(Remove|RemoveAll|Rename|Chmod|Chown|Chtimes)|.*\\.(Print|Printf|Println)|os\\.(Create|NewFile|Open|OpenFile)|.*\\.(Fprint|Fprintf|Fprintln))"
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

